### ISSUE TITLE
Remove the node 5.6 dependency

### ISSUE THREAD

**Issue by pgambling** [experoinc/react-client-starter#3]

**Comment by bman654** [comment]
yeah I think this was a transient issue that Karim had in the Way Back.  I (and others) have used this repo with any recent node version.

**Comment by pgambling** [comment]
Oh great. I expected we needed to bump a dependency version. I'll take this and confirm it works with the latest node version since we want to use that for Acton.

**Comment by pgambling** [comment]
Tested it out with node the latest LTS release (6.9.5) and the latest version (7.5.0). No problems encountered.
